# Generated by Django 3.1.2 on 2020-11-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catalog',
            new_name='category',
        ),
    ]
