# Generated by Django 3.1.4 on 2020-12-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='alias',
            field=models.CharField(default='default-page', max_length=250),
            preserve_default=False,
        ),
    ]
