# Generated by Django 3.1.4 on 2020-12-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20201202_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='alias',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
