# Generated by Django 3.1.2 on 2020-11-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_busket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image1', upload_to='products'),
            preserve_default=False,
        ),
    ]
