# Generated by Django 3.1.3 on 2020-11-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='noimage.png', upload_to='products'),
            preserve_default=False,
        ),
    ]
